version: '3.8' 
services: 
  db: 
    image: postgres:17 
    environment: 
      POSTGRES_DB: coinssjj
      POSTGRES_USER: admin 
      POSTGRES_PASSWORD: sa 
    ports: 
      - "5432:5432" 
    volumes: 
      - postgres_data:/var/lib/postgresql/data 
volumes: 
  postgres_data: 
